### ISSUE TITLE
Massiver Fehler unter Windows 

### ISSUE THREAD

**Issue by Hini2001** [AlCalzone/ioBroker.ble#403]
Moin,

mein ioBroker läuft auf einem Beelink BT3 Pro und das sehr sehr gut und zuverlässig.
Als Betriebssystem ist Windows 10 (da ich absolut ein Linux-NICHT-Könner bin und ja, sicherlich auch wenig zu faul mich damit zu befassen). :-(

Nun zu meinem Problem und ich habe jetzt über all gesucht und nix gefunden.
Ich würde gerne den BLE Adapter zum laufen bringen und so die Flower Sensoren auslesen um z.B. eine Alexa-Ansage zu erhalten, wenn mal wieder gegossen werden muss.

Nun bekomme ich aber den Adapter nicht zum laufen. Viel Schlimmer noch. Allein die Installation des Adapter zerschießt die gesamte Installation und dies konnte ich nur durch eine komplette Neuinstallation wieder beheben.

Habe dann heute auf meinem Laptop einmal einen Testserver installiert und versucht hier den BLE Adapter einzubinden. Aber auch hier wurde auf einer ganz frischen Plattform die gesamte Installation zerschossen. 

Das Log dazu sieht folgend aus:
```
2020-05-17 09:57:20.466 - info: host.Laptop-2(TestServer) iobroker add ble --host Laptop-2(TestServer)
2020-05-17 09:57:22.954 - info: host.Laptop-2(TestServer) iobroker NPM version: 6.11.3
2020-05-17 09:57:22.956 - info: host.Laptop-2(TestServer) iobroker npm install iobroker.ble@0.11.0 --loglevel error --prefix "C:/Program Files/iobroker/TestServer" (System call)
2020-05-17 09:57:31.842 - info: host.Laptop-2(TestServer) iobroker prebuild-install
2020-05-17 09:57:31.844 - info: host.Laptop-2(TestServer) iobroker
2020-05-17 09:57:31.844 - info: host.Laptop-2(TestServer) iobroker info begin Prebuild-install version 5.3.3
2020-05-17 09:57:31.850 - info: host.Laptop-2(TestServer) iobroker prebuild-install
2020-05-17 09:57:31.851 - info: host.Laptop-2(TestServer) iobroker info looking for cached prebuild @ C:\Program Files\iobroker\TestServer\env\npm-cache\_prebuilds\b5fa15-usb-v1.6.3-node-v64-win32-x64.tar.gzprebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v64-win32-x64.tar.gz
2020-05-17 09:57:32.800 - info: host.Laptop-2(TestServer) iobroker prebuild-install
2020-05-17 09:57:32.802 - info: host.Laptop-2(TestServer) iobroker http 200 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v64-win32-x64.tar.gz
2020-05-17 09:57:32.806 - info: host.Laptop-2(TestServer) iobroker prebuild-install
2020-05-17 09:57:32.807 - info: host.Laptop-2(TestServer) iobroker info downloading to @ C:\Program Files\iobroker\TestServer\env\npm-cache\_prebuilds\b5fa15-usb-v1.6.3-node-v64-win32-x64.tar.gz.18324-3ace256454629.tmp
2020-05-17 09:57:33.118 - info: host.Laptop-2(TestServer) iobroker prebuild-install
2020-05-17 09:57:33.120 - info: host.Laptop-2(TestServer) iobroker info renaming to @ C:\Program Files\iobroker\TestServer\env\npm-cache\_prebuilds\b5fa15-usb-v1.6.3-node-v64-win32-x64.tar.gzprebuild-install info unpacking @ C:\Program Files\iobroker\TestServer\env\npm-cache\_prebuilds\b5fa15-usb-v1.6.3-node-v64-win32-x64.tar.gz
2020-05-17 09:57:33.175 - info: host.Laptop-2(TestServer) iobroker prebuild-install
2020-05-17 09:57:33.176 - info: host.Laptop-2(TestServer) iobroker info unpack resolved to C:\Program Files\iobroker\TestServer\node_modules\iobroker.ble\node_modules\usb\build\Release\usb_bindings.node
2020-05-17 09:57:33.245 - info: host.Laptop-2(TestServer) iobroker prebuild-install info
2020-05-17 09:57:33.247 - info: host.Laptop-2(TestServer) iobroker unpack required C:\Program Files\iobroker\TestServer\node_modules\iobroker.ble\node_modules\usb\build\Release\usb_bindings.node successfullyprebuild-install info install Successfully installed prebuilt binary!
2020-05-17 09:57:44.481 - info: host.Laptop-2(TestServer) iobroker gyp
2020-05-17 09:57:44.481 - info: host.Laptop-2(TestServer) iobroker
2020-05-17 09:57:44.482 - info: host.Laptop-2(TestServer) iobroker ERR! build error
2020-05-17 09:57:44.482 - info: host.Laptop-2(TestServer) iobroker gyp
2020-05-17 09:57:44.482 - info: host.Laptop-2(TestServer) iobroker
2020-05-17 09:57:44.483 - info: host.Laptop-2(TestServer) iobroker ERR!
2020-05-17 09:57:44.483 - info: host.Laptop-2(TestServer) iobroker stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
2020-05-17 09:57:44.484 - info: host.Laptop-2(TestServer) iobroker gyp ERR!
2020-05-17 09:57:44.484 - info: host.Laptop-2(TestServer) iobroker stack
2020-05-17 09:57:44.485 - info: host.Laptop-2(TestServer) iobroker at ChildProcess.onExit (C:\Program Files\iobroker\TestServer\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:193:23)gyp
2020-05-17 09:57:44.486 - info: host.Laptop-2(TestServer) iobroker ERR! stack at ChildProcess.emit (events.js:198:13)gyp
2020-05-17 09:57:44.486 - info: host.Laptop-2(TestServer) iobroker ERR! stack
2020-05-17 09:57:44.488 - info: host.Laptop-2(TestServer) iobroker at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)gyp ERR!
2020-05-17 09:57:44.489 - info: host.Laptop-2(TestServer) iobroker
2020-05-17 09:57:44.490 - info: host.Laptop-2(TestServer) iobroker System
2020-05-17 09:57:44.492 - info: host.Laptop-2(TestServer) iobroker Windows_NT 10.0.18362
2020-05-17 09:57:44.493 - info: host.Laptop-2(TestServer) iobroker gyp
2020-05-17 09:57:44.494 - info: host.Laptop-2(TestServer) iobroker
2020-05-17 09:57:44.497 - info: host.Laptop-2(TestServer) iobroker ERR!
2020-05-17 09:57:44.498 - info: host.Laptop-2(TestServer) iobroker command "C:\\Program Files\\iobroker\\TestServer\\nodejs\\node.exe" "C:\\Program Files\\iobroker\\TestServer\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Program Files\\iobroker\\TestServer\\node_modules\\iobroker.ble\\node_modules\\@abandonware\\bluetooth-hci-socket\\lib\\binding\\binding.node" "--module_name=binding" "--module_path=C:\\Program Files\\iobroker\\TestServer\\node_modules\\iobroker.ble\\node_modules\\@abandonware\\bluetooth-hci-socket\\lib\\binding" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"gyp
2020-05-17 09:57:44.499 - info: host.Laptop-2(TestServer) iobroker
2020-05-17 09:57:44.499 - info: host.Laptop-2(TestServer) iobroker ERR! cwd C:\Program Files\iobroker\TestServer\node_modules\iobroker.ble\node_modules\@abandonware\bluetooth-hci-socket
2020-05-17 09:57:44.501 - info: host.Laptop-2(TestServer) iobroker gyp ERR! node -v v10.17.0gyp ERR!
2020-05-17 09:57:44.502 - info: host.Laptop-2(TestServer) iobroker
2020-05-17 09:57:44.502 - info: host.Laptop-2(TestServer) iobroker node-gyp -v
2020-05-17 09:57:44.503 - info: host.Laptop-2(TestServer) iobroker v5.0.3
2020-05-17 09:57:44.505 - info: host.Laptop-2(TestServer) iobroker gyp ERR! not ok
2020-05-17 09:57:44.514 - info: host.Laptop-2(TestServer) iobroker node-pre-gyp
2020-05-17 09:57:44.515 - info: host.Laptop-2(TestServer) iobroker ERR! build error node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\iobroker\TestServer\nodejs\node.exe C:\Program Files\iobroker\TestServer\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Program Files\iobroker\TestServer\node_modules\iobroker.ble\node_modules\@abandonware\bluetooth-hci-socket\lib\binding\binding.node --module_name=binding --module_path=C:\Program Files\iobroker\TestServer\node_modules\iobroker.ble\node_modules\@abandonware\bluetooth-hci-socket\lib\binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)node-pre-gyp
2020-05-17 09:57:44.515 - info: host.Laptop-2(TestServer) iobroker ERR! stack at ChildProcess. (C:\Program Files\iobroker\TestServer\node_modules\iobroker.ble\node_modules\node-pre-gyp\lib\util\compile.js:83:29)node-pre-gyp ERR! stack at ChildProcess.emit (events.js:198:13)node-pre-gyp ERR! stack
2020-05-17 09:57:44.516 - info: host.Laptop-2(TestServer) iobroker at maybeClose (internal/child_process.js:982:16)node-pre-gyp ERR!
2020-05-17 09:57:44.516 - info: host.Laptop-2(TestServer) iobroker stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2020-05-17 09:57:44.517 - info: host.Laptop-2(TestServer) iobroker node-pre-gyp
2020-05-17 09:57:44.517 - info: host.Laptop-2(TestServer) iobroker ERR! System Windows_NT 10.0.18362node-pre-gyp ERR! command "C:\\Program Files\\iobroker\\TestServer\\nodejs\\node.exe" "C:\\Program Files\\iobroker\\TestServer\\node_modules\\iobroker.ble\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp
2020-05-17 09:57:44.518 - info: host.Laptop-2(TestServer) iobroker ERR! cwd C:\Program Files\iobroker\TestServer\node_modules\iobroker.ble\node_modules\@abandonware\bluetooth-hci-socketnode-pre-gyp ERR!
2020-05-17 09:57:44.519 - info: host.Laptop-2(TestServer) iobroker node -v v10.17.0node-pre-gyp ERR! node-pre-gyp -v v0.14.0node-pre-gyp ERR! not ok
2020-05-17 09:57:49.866 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) install adapter ble
2020-05-17 09:57:49.891 - info: host.Laptop-2(TestServer) iobroker upload [7] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/words.js words.js application/javascript
2020-05-17 09:57:49.967 - info: host.Laptop-2(TestServer) iobroker upload [6] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/style.css style.css text/css
2020-05-17 09:57:50.028 - info: host.Laptop-2(TestServer) iobroker upload [5] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/index_m.html index_m.html text/html
2020-05-17 09:57:50.096 - info: host.Laptop-2(TestServer) iobroker upload [4] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/index.html index.html text/html
2020-05-17 09:57:50.161 - info: host.Laptop-2(TestServer) iobroker upload [3] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/build/index.map build/index.map application/json
2020-05-17 09:57:50.233 - info: host.Laptop-2(TestServer) iobroker upload [2] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/build/index.js.map build/index.js.map application/json
2020-05-17 09:57:50.306 - info: host.Laptop-2(TestServer) iobroker upload [1] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/build/index.js build/index.js application/javascript
2020-05-17 09:57:50.374 - info: host.Laptop-2(TestServer) iobroker upload [0] ble.admin C:/Program Files/iobroker/TestServer/node_modules/iobroker.ble/admin/ble.png ble.png image/png
2020-05-17 09:57:50.487 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble created/updated
2020-05-17 09:57:50.542 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) create instance ble
2020-05-17 09:57:50.547 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object ble.0.options.allowNewDevices created
2020-05-17 09:57:50.578 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object ble.0.options created
2020-05-17 09:57:50.609 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object ble.0.info.driverState created
2020-05-17 09:57:50.641 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object ble.0.info.connection created
2020-05-17 09:57:50.669 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object ble.0.info created
2020-05-17 09:57:50.701 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.sigKill created
2020-05-17 09:57:50.733 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.eventLoopLag created
2020-05-17 09:57:50.761 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.outputCount created
2020-05-17 09:57:50.789 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.inputCount created
2020-05-17 09:57:50.817 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.uptime created
2020-05-17 09:57:50.844 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.memRss created
2020-05-17 09:57:50.876 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.memHeapTotal created
2020-05-17 09:57:50.908 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.memHeapUsed created
2020-05-17 09:57:50.940 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.cputime created
2020-05-17 09:57:50.968 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.cpu created
2020-05-17 09:57:50.996 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.compactMode created
2020-05-17 09:57:51.029 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.connected created
2020-05-17 09:57:51.060 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0.alive created
2020-05-17 09:57:51.109 - info: host.Laptop-2(TestServer) iobroker host.Laptop-2(TestServer) object system.adapter.ble.0 created
2020-05-17 09:57:52.122 - info: host.Laptop-2(TestServer) iobroker exit 0
2020-05-17 09:57:53.623 - info: host.Laptop-2(TestServer) instance system.adapter.ble.0 started with pid 15656
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[0]: internal/modules/cj
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]: s/loader.js:638
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]: throw err;
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]: ^
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]:
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]: Error: Cannot find module 'inherits'
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2020-05-17 09:57:54.058 - error: host.Laptop-2(TestServer) Caught by controller[1]: at Module.require (internal/modules/cjs/loader.js:692:17)
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[1]: at require (inte
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[2]: rnal/modules/cjs/helpers.js:25:18)
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[2]: at Object.error:="" host.laptop-2(testserver)="" caught="" by="" controller[3]:="" ous=""> (C:\Prog
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[4]: ram Files\iobroker\TestServer\node_mo
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[5]: dules\winston\node_modules\reada
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[6]: ble-stream\lib\_stream_readable
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[7]: .js:92:1)
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[7]: at Module._compil
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[8]: e (internal/modules/cjs/loader
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[9]: .js:778:30)
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[9]: at Object.Modul
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[10]: e._extensions..js (internal/m
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[11]: odules/cjs/loader.js:789:10)
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[12]: at Module.load (internal/
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[13]: modules/cjs/loader.js:653:32)
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[13]:
2020-05-17 09:57:54.059 - error: host.Laptop-2(TestServer) Caught by controller[14]: at tryModuleLoad (internal
2020-05-17 09:57:54.060 - error: host.Laptop-2(TestServer) Caught by controller[15]: /modules/cjs/loader.js:593:12)
2020-05-17 09:57:54.060 - error: host.Laptop-2(TestServer) Caught by controller[15]:
2020-05-17 09:57:54.060 - error: host.Laptop-2(TestServer) Caught by controller[16]: at Function.Module._load (in
2020-05-17 09:57:54.060 - error: host.Laptop-2(TestServer) Caught by controller[17]: ternal/modules/cjs/loader.js:
2020-05-17 09:57:54.060 - error: host.Laptop-2(TestServer) Caught by controller[18]: 585:3)
2020-05-17 09:57:54.060 - error: host.Laptop-2(TestServer) instance system.adapter.ble.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
```

Wenn man dann jetzt versucht den Adapter zu deinstallieren (oder auch jegliche Andere Aktion, wie Adapterupdates oder irgendwas neuzuinstallieren kommt folgende Fehlermeldung:

```
2020-05-17 09:58:41.421 - info: host.Laptop-2(TestServer) iobroker del ble.0
2020-05-17 09:58:42.542 - error: host.Laptop-2(TestServer) iobroker C:\Program Files\io
2020-05-17 09:58:42.543 - error: host.Laptop-2(TestServer) iobroker broker\TestServer\node_modules\standard-as-callback\built\index.js:6
throw e;
^
Error: Cannot find module 'safe-buffer'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at requir
2020-05-17 09:58:42.543 - error: host.Laptop-2(TestServer) iobroker e (internal/modules/cjs/helpers.js:25:18)
at Object. (C:\Program Files\iobroker\TestServer\node_modules\request\lib\helpers.js:5:14)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._
2020-05-17 09:58:42.544 - error: host.Laptop-2(TestServer) iobroker extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/m
2020-05-17 09:58:42.544 - error: host.Laptop-2(TestServer) iobroker odules/cjs/loader.js:585:3)
2020-05-17 09:58:42.551 - info: host.Laptop-2(TestServer) iobroker exit 
```
Und dann geht nix mehr. Sobald der Serverdienst einmal beendet wurde, startet er nicht wieder neu. Und dann half nur eine Neuinstallation (oder gibt es eine andere Möglichkeit dies wieder rückgängig zu machen?)

Gibt es eine Möglichkeit den BLE - Adapter auf einer Windows-IoBroker-Umgebung zu installieren und zu nutzen? Müssen irgendwelche Schritte vorab beachtet werden?

Ich hoffe Ihr könnt mir helfen, denn so einen Aufwand wie gestern will ich tunlichst zukünftig vermeiden.

Beste Grüße
Hinrich

**Comment by AlCalzone** [comment]
Wie hast du installiert? Anscheinend hat der alte Installer das Problem, dass unter manchen Umständen Pakete verschwinden (wie hier zu sehen).

**Comment by Hini2001** [comment]
Die Installation mit der Windows Installer Version von der ioBroker Homepage (stand 23.11.19). Hab keinen neueren gefunden. :-/ 
Und den Adapter im Anschluss via der Admin Oberfläche.
Mehr nicht.
Muss man unter Windows noch irgendwelche anderen Dinge installieren? Vorab?

**Comment by AlCalzone** [comment]
Am besten schaust du mal hier nach, ob der schon nutzbar ist:
https://forum.iobroker.net/topic/29778/windows-installer-2

Ich kenne mich mit der Windows-Problematik nicht so aus.

**Comment by Hini2001** [comment]
Naja aber wird damit das Problem behoben? Alle anderen Adapter funktionieren einwandfrei. Ebenso die Installation und Deinstallation. Es handelt sich dabei nur um den BLE Adapter.

**Comment by AlCalzone** [comment]
Ich erkenne aus dem Log nicht, was das Problem ist. Ich weiß nur, dass der Windows-Installer das Problem hat, dass unter bestimmten Umständen Ordner gelöscht werden, die nicht gelöscht werden dürfen. Eventuell liegt es daran, dass ein natives Modul kompiliert wird - tritt also nicht bei allen Adaptern auf. Ist auch das erste Mal, dass ich bei BLE davon höre, bei knapp 2.500 Installationen.

**Comment by Hini2001** [comment]
Hmmm... ok. 
Habe mir mal den neuen Installer runtergeladen. Das Problem ist, mit dem installiert er keine Server Instanz... keine Ahnung, ob das nicht vorgesehen ist?!
Habe jetzt noch mal einen neuen Server installiert zum testen. Mal sehen, ob es dieses mal klappt. :-/ oder muss ich noch irgendwie noble installieren vorab? Ich steige da nicht immer und überall durch.

**Comment by AlCalzone** [comment]
Nein, der Adapter installiert automatisch alles Nötige mit.

**Comment by AlCalzone** [comment]
@Hini2001 Installiert auch dieser Link nichts?
![grafik](https://user-images.githubusercontent.com/17641229/82306315-311cdd80-99bf-11ea-9b5d-c3c80fc8103b.png)

**Comment by Hini2001** [comment]
Leider nein. 😣
Zumindest keine neue Iobroker Instanz? 🤷‍♂️

**Comment by AlCalzone** [comment]
Hm blöd. Ich weiß leider auch nicht was da der Status ist. Ggf. klärt sich das am Donnerstag.

**Comment by AlCalzone** [comment]
![grafik](https://user-images.githubusercontent.com/17641229/91188646-d26bac00-e6f1-11ea-8080-7df7e3876213.png)
