### ISSUE TITLE
Keine Daten vom BLE

### ISSUE THREAD

**Issue by Sigi74** [AlCalzone/ioBroker.ble#836]
Der Adapter wird grün und im Log ist beim Starten vom iobroker nichts ersichtlich.
Da er Grün wird ist es mir anfänglich gar nicht aufgefallen, dass keine Daten mehr geloggt werden (seit einem Updaten Mitte Dezember).
Wenn ich den Adapter neu starte komm im Log:
```
error	Cannot find module '../build/Release/bluetooth_hci_socket.node'Require stack:- /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js- /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/index.js- /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js- /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js- /opt/iobroker/node_modules/@abandonware/noble/lib/resolve-bindings.js- /opt/iobroker/node_modules/@abandonware/noble/with-custom-binding.js- /opt/iobroker/node_modules/@abandonware/noble/index.js- /opt/iobroker/node_modules/iobroker.ble/build/scanProcess.js
```

Ein iob fix läuft durch ohne Fehler und bringt auch keine Besserung.
Nodeversion:
/usr/bin/nodejs         v18.19.0
/usr/bin/node           v18.19.0
/usr/bin/npm            10.2.3
/usr/bin/npx            10.2.3
/usr/bin/corepack       0.22.0

Wenn ich `npm i iobroker.ble --production --unsafe-perm` ausführe bekomme ich folgende Meldung:
```
pi@ioBroker-Proxmox:/opt/iobroker/node_modules/iobroker.ble$ sudo npm i iobroker.ble --production --unsafe-perm
npm WARN config production Use `--omit=dev` instead.
npm notice
npm notice New minor version of npm available! 10.2.3 -> 10.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.4.0
npm notice Run npm install -g npm@10.4.0 to update!
npm notice
npm ERR! code 1
npm ERR! path /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.19.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.19.0/node-v18.19.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.19.0/node-v18.19.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.19.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.19.0/SHASUMS256.txt
npm ERR! (node:112723) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.19.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.19.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.19.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!                       ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
npm ERR!     build_file_contents = open(build_file_path, "rU").read()
npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/opt/iobroker/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Linux 6.1.0-16-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v18.19.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-01T22_02_53_724Z-debug-0.log
```

Wenn ich versuche den BLE neu zu installieren wird er im Anschluss nicht mehr grün und die Fehlermeldungen bleiben die selben.
Ich habe keinen Plan mehr was ich versuchen sollte, oder wo das Problem liegen könnte

**Comment by AlCalzone** [comment]
Wurde hier schon mal behandelt:
https://github.com/AlCalzone/ioBroker.ble/issues/801#issuecomment-1653167460

Versuch mal, `npm` zu aktualisieren. Oder wenn das nicht hilft: https://github.com/AlCalzone/ioBroker.ble/issues/801#issuecomment-1657094405

**Comment by Sigi74** [comment]
Super danke,
npm hatte ich schon versucht, hatte nichts gebracht, aber https://github.com/AlCalzone/ioBroker.ble/issues/801#issuecomment-1657094405 hat sofort geholfen 
Danke für die schnelle Hilfe, versuche es schon seit Tagen zu lösen

**Comment by klein0r** [comment]
Bekomme den gleichen Fehler. npm und node ist soweit aktuell.

```
Cannot find module '@abandonware/bluetooth-hci-socket'Require stack:- /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js- /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js- /opt/iobroker/node_modules/@abandonware/noble/lib/resolve-bindings.js- /opt/iobroker/node_modules/@abandonware/noble/with-custom-binding.js- /opt/iobroker/node_modules/@abandonware/noble/index.js- /opt/iobroker/node_modules/iobroker.ble/build/scanProcess.js
```

```
pi@raspberrypi:~ $ npm -v
10.2.3
pi@raspberrypi:~ $ node -v
v18.19.0
```

Gelöst mit

```
cd /opt/iobroker/node_modules
sudo -H -u iobroker npm i @abandonware/bluetooth-hci-socket --omit=dev
```

**Comment by jenbenn** [comment]
Ich habe offenbar dasselbe Problem im Iobroker unter windows.  Wie führe ich den Befehl omit=dev Befehl dort aus?
