### ISSUE TITLE
gelöst: Probleme iobroker.ble 0.14.0 zu installieren

### ISSUE THREAD

**Issue by thomke67** [AlCalzone/ioBroker.ble#868]
Hallo,

ich habe Probleme den o.a. Adapter zu installieren.
Es klappt nicht über die Adapter Installlation in IObroker noch über die Konsole.

Konsole
pi@raspberrypi:~ $ iobroker install ble
NPM version: 10.9.0
Installing iobroker.ble@0.14.0... (System call)
npm error code 1
npm error path /opt/iobroker/node_modules/@abandonware/noble
npm error command failed
npm error command sh -c node-gyp-build
npm error Traceback (most recent call last):
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm error     import gyp  # noqa: E402
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm error     import gyp.input
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module>
npm error     import gyp.common
npm error   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435
npm error     if CC := os.environ.get("CC_target") or os.environ.get("CC"):
npm error            ^
npm error SyntaxError: invalid syntax
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:517:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm error gyp ERR! System Linux 5.10.103-v7l+
npm error gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/noble
npm error gyp ERR! node -v v18.20.2
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-10-10T08_42_46_387Z-debug-0.log
host.raspberrypi Cannot install iobroker.ble@0.14.0: 1
pi@raspberrypi:~ $

Iobroker:
$ iobroker add ble auto --host raspberrypi --debug

NPM version: 10.9.0

Installing iobroker.ble@0.14.0... (System call)

npm warn deprecated npmlog@5.0.1: This package is no longer supported.

npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported

npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.

npm warn deprecated gauge@3.0.2: This package is no longer supported.

> @abandonware/bluetooth-hci-socket@0.5.3-12 install> node-pre-gyp install --build-from-source

node-pre-gyp info it worked if it ends with ok

node-pre-gyp info using node-pre-gyp@1.0.11

node-pre-gyp info using node@18.20.2 | linux | arm

node-pre-gyp info build requesting source compile

gyp info it worked if it ends with ok

gyp info using node-gyp@10.2.0

gyp info using node@18.20.2 | linux | arm

gyp info ok

gyp info using node-gyp@10.2.0gyp info using node@18.20.2 | linux | arm

gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3

gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/18.20.2/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.20.2',gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.20.2/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]

Traceback (most recent call last):

File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module> import gyp # noqa: E402 File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module> import gyp.input File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module> import gyp.common File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435 if CC := os.environ.get("CC_target") or os.environ.get("CC"): ^SyntaxError: invalid syntax

gyp ERR! System Linux 5.10.103-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--build-from-source" "--module=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" "--module_name=bluetooth_hci_socket" "--module_path=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"

gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socketgyp ERR! node -v v18.20.2gyp ERR! node-gyp -v v10.2.0gyp ERR! not ok

node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --build-from-source --module=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)node-pre-gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)node-pre-gyp ERR! stack at ChildProcess.emit (node:events:517:28)node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1098:16)node-pre-gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:303:5)

node-pre-gyp ERR! node-pre-gyp -v v1.0.11node-pre-gyp ERR! not ok Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --build-from-source --module=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)

> @abandonware/noble@1.9.2-25 install> node-gyp-build

gyp info it worked if it ends with ok

gyp info using node-gyp@10.2.0gyp info using node@18.20.2 | linux | arm

gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3

gyp info spawn args [gyp info spawn args '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/@abandonware/noble/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/18.20.2/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.20.2',gyp info spawn args '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.20.2/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/noble',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]

Traceback (most recent call last): File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module> import gyp # noqa: E402 File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module> import gyp.input File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module> import gyp.common File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435 if CC := os.environ.get("CC_target") or os.environ.get("CC"): ^SyntaxError: invalid syntax

gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-gyp/lib/configure.js:317:18)gyp ERR! stack at ChildProcess.emit (node:events:517:28)gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)gyp ERR! System Linux 5.10.103-v7l+gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/noblegyp ERR! node -v v18.20.2gyp ERR! node-gyp -v v10.2.0gyp ERR! not ok

npm error code 1npm error path /opt/iobroker/node_modules/@abandonware/noblenpm error command failednpm error command sh -c node-gyp-build

npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-10-10T08_51_07_952Z-debug-0.log

npm warn deprecated npmlog@5.0.1: This package is no longer supported.npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supportednpm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.npm warn deprecated gauge@3.0.2: This package is no longer supported.node-pre-gyp info it worked if it ends with oknode-pre-gyp info using node-pre-gyp@1.0.11node-pre-gyp info using node@18.20.2 | linux | armnode-pre-gyp info build requesting source compilegyp info it worked if it ends with okgyp info using node-gyp@10.2.0gyp info using node@18.20.2 | linux | armgyp info ok gyp info it worked if it ends with okgyp info using node-gyp@10.2.0gyp info using node@18.20.2 | linux | armgyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"gyp info spawn /usr/bin/python3gyp info spawn args [gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/18.20.2/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.20.2',gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.20.2/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]Traceback (most recent call last): File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module> import gyp # noqa: E402 File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module> import gyp.input File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module> import gyp.common File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435 if CC := os.environ.get("CC_target") or os.environ.get("CC"): ^SyntaxError: invalid syntaxgyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)gyp ERR! stack at ChildProcess.emit (node:events:517:28)gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)gyp ERR! System Linux 5.10.103-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--build-from-source" "--module=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" "--module_name=bluetooth_hci_socket" "--module_path=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socketgyp ERR! node -v v18.20.2gyp ERR! node-gyp -v v10.2.0gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --build-from-source --module=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)node-pre-gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)node-pre-gyp ERR! stack at ChildProcess.emit (node:events:517:28)node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1098:16)node-pre-gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:303:5)node-pre-gyp ERR! System Linux 5.10.103-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--build-from-source"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socketnode-pre-gyp ERR! node -v v18.20.2node-pre-gyp ERR! node-pre-gyp -v v1.0.11node-pre-gyp ERR! not ok gyp info it worked if it ends with okgyp info using node-gyp@10.2.0gyp info using node@18.20.2 | linux | armgyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"gyp info spawn /usr/bin/python3gyp info spawn args [gyp info spawn args '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/@abandonware/noble/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/18.20.2/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.20.2',gyp info spawn args '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.20.2/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/noble',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]Traceback (most recent call last): File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module> import gyp # noqa: E402 File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module> import gyp.input File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 8, in <module> import gyp.common File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 435 if CC := os.environ.get("CC_target") or os.environ.get("CC"): ^SyntaxError: invalid syntaxgyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-gyp/lib/configure.js:317:18)gyp ERR! stack at ChildProcess.emit (node:events:517:28)gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)gyp ERR! System Linux 5.10.103-v7l+gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/@abandonware/noblegyp ERR! node -v v18.20.2gyp ERR! node-gyp -v v10.2.0gyp ERR! not ok npm error code 1npm error path /opt/iobroker/node_modules/@abandonware/noblenpm error command failednpm error command sh -c node-gyp-buildnpm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-10-10T08_51_07_952Z-debug-0.log

host.raspberrypi Cannot install iobroker.ble@0.14.0: 1

ERROR: Process exited with code 25

Gruß
Thomas

**Comment by thomke67** [comment]
Ich ziehe mein Problemanfrage zurück, weil es augenscheinlich an meinem OS lag. Nach einem Update von Buster auf Bookworm funktioniert die Installation einwandfrei.

Gruß,
Tomas
